version: '3'

services:
  ducket-database:
    image: mysql/mysql-server:8.0.23
    restart: unless-stopped
    container_name: ducket-database
    environment:
      - TZ=${DB_TZ}
      - MYSQL_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=ducket-db
      - MYSQL_TCP_PORT=3310
    ports:
      - 3310:3310
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 2s
      retries: 3
    command: ['mysqld', '--character-set-server=utf8mb4', '--log_bin_trust_function_creators=1']

  ducket-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ducket-backend
    depends_on:
      - ducket-database
    restart: unless-stopped
    environment:
      - DB_DATA_PATH=resources/db/data
      - DB_HOST=ducket-database
      - DB_PORT=3310
      - DB_NAME=ducket-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_SECRET=${APP_SECRET}
      - APP_PORT=8100
    ports:
      - 8100:8100
    volumes:
      - backend_data:/app/resources/db/data
      - backend_logs:/app/logs

  ducket-prometheus:
    image: prom/prometheus:v2.32.0
    container_name: ducket-prometheus
    depends_on:
      - ducket-backend
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./resources/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: [ '--config.file=/etc/prometheus/prometheus.yml' ]

  ducket-loki:
    image: grafana/loki:2.4.1
    container_name: ducket-loki
    depends_on:
      - ducket-backend
    ports:
      - 3100:3100
    volumes:
      - ./resources/monitoring/loki.yaml:/etc/loki/config.yaml
      - loki_data:/data/loki
    command: ['-config.file=/etc/loki/local-config.yaml']

  ducket-promtail:
    image: grafana/promtail:2.4.1
    container_name: ducket-promtail
    depends_on:
      - ducket-backend
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./logs:/var/log
      - ./resources/monitoring/promtail.yaml:/etc/promtail/config.yaml
    command: ['-config.file=/etc/promtail/config.yaml']

  ducket-grafana:
    image: grafana/grafana-oss:8.1.8
    container_name: ducket-grafana
    depends_on:
      - ducket-backend
      - ducket-prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GR_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GR_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    user: "104"

volumes:
  database_data:
  backend_data:
  backend_logs:
  loki_data:
  prometheus_data:
  grafana_data:
