version: '3'

services:
  db:
    image: mysql:8.0.19
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=UTC
    ports:
      - 3310:${DB_PORT}
    command: ['mysqld', '--character-set-server=utf8mb4']
    volumes:
      - app_database:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    restart: unless-stopped
    ports:
      - 8100:${PORT}
    volumes:
      - app_service:/bin/runner

  prometheus:
    image: prom/prometheus:v2.32.0
    restart: unless-stopped
    ports:
      - 3570:9090
    volumes:
      - ./resources/monitoring:/prometheus
    command:
      - "--config.file=/prometheus/prometheus.yml"
    links:
      - backend

  grafana:
    image: grafana/grafana-oss:8.1.8
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    links:
      - backend
      - prometheus
    user: "104"

volumes:
  app_database:
  app_service:
  grafana_data:
  prometheus_data: